services:
  - type: web
    name: personalized-finance-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
